import { User, ProductionReport, ProductionEntry, EquipmentTarget, ProductionPeriodTarget } from '../types';
import { format } from 'date-fns';

const planDate = format(new Date(), 'yyyy-MM-dd');
const actualDate = format(new Date(Date.now() - 86400000), 'yyyy-MM-dd');
const previousActualDate = format(new Date(Date.now() - 86400000 * 2), 'yyyy-MM-dd');

// 데모 유저 목록
export const DEMO_USERS: User[] = [
  {
    id: 'user-admin',
    name: '관리자',
    email: 'admin@forging.com',
    employee_no: '10001',
    role: 'admin',
    assigned_equipment: ['P15', 'P5', 'R/M'],
    assigned_shift: null,
    can_write: true,
    can_edit: true,
    can_delete: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'user-kim-hoegeun',
    name: '김회근 부장',
    email: 'hoegeun.kim@forging.com',
    employee_no: '10002',
    role: 'manager',
    assigned_equipment: ['P15', 'P5', 'R/M'],
    assigned_shift: null,
    can_write: true,
    can_edit: true,
    can_delete: false,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'user-kim-hyun',
    name: '김현 차장',
    email: 'hyun.kim@forging.com',
    employee_no: '10003',
    role: 'user',
    assigned_equipment: ['P15'],
    assigned_shift: null,
    can_write: true,
    can_edit: false,
    can_delete: false,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'user-koo-byeongjun',
    name: '구병준 차장',
    email: 'byeongjun.koo@forging.com',
    employee_no: '10004',
    role: 'user',
    assigned_equipment: ['P5'],
    assigned_shift: null,
    can_write: true,
    can_edit: false,
    can_delete: false,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'user-woo-jaehan',
    name: '우재한 과장',
    email: 'jaehan.woo@forging.com',
    employee_no: '10005',
    role: 'user',
    assigned_equipment: ['R/M'],
    assigned_shift: null,
    can_write: true,
    can_edit: false,
    can_delete: false,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'user-lee-eunseo',
    name: '이은서 대리',
    email: 'eunseo.lee@forging.com',
    employee_no: '10006',
    role: 'manager',
    assigned_equipment: ['P15', 'P5', 'R/M'],
    assigned_shift: null,
    can_write: true,
    can_edit: true,
    can_delete: false,
    created_at: '2026-01-01T00:00:00Z',
  },
];

// 데모 보고서
export const DEMO_REPORTS: ProductionReport[] = [
  {
    id: 'report-today',
    report_date: actualDate,
    next_plan_date: planDate,
    status: 'collecting',
    created_by: 'user-admin',
    created_at: planDate + 'T08:00:00Z',
    updated_at: planDate + 'T08:00:00Z',
  },
  {
    id: 'report-yesterday',
    report_date: previousActualDate,
    next_plan_date: actualDate,
    status: 'closed',
    created_by: 'user-admin',
    closed_by: 'user-admin',
    closed_at: actualDate + 'T18:00:00Z',
    created_at: actualDate + 'T08:00:00Z',
    updated_at: actualDate + 'T18:00:00Z',
  },
];

// 데모 실적 데이터
export const DEMO_ENTRIES: ProductionEntry[] = [
  // 오늘 - P15 주간 (제출완료)
  {
    id: 'entry-1',
    report_id: 'report-today',
    user_id: 'user-kim-hyun',
    user_name: '김현 차장',
    equipment: 'P15',
    shift: '주간',
    product_plan: 100000,
    product_actual: 96000,
    billet_plan: 100000,
    billet_actual: 98000,
    next_product_plan: 100000,
    next_billet_plan: 100000,
    reason_category: '설비 문제',
    reason_detail: '2호 해머 유압 실린더 씰 교체로 2.5시간 손실 발생. 보전팀 즉시 투입하여 11:30 복구 완료.',
    action_today: '복구 후 잔여 시간 최대 가동. 금형 준비 사전 완료.',
    recovery_plan: '금일 주간에 P15 추가 4,000KG 생산 계획. 잔업 1시간 적용.',
    support_request: '보전팀 예방 점검 주기 단축 요청',
    submit_status: 'submitted',
    submitted_at: planDate + 'T17:30:00Z',
    created_at: planDate + 'T09:00:00Z',
    updated_at: planDate + 'T17:30:00Z',
  },
  // 오늘 - P5 주간 (임시저장)
  {
    id: 'entry-2',
    report_id: 'report-today',
    user_id: 'user-koo-byeongjun',
    user_name: '구병준 차장',
    equipment: 'P5',
    shift: '주간',
    product_plan: 40000,
    product_actual: 38000,
    billet_plan: 30000,
    billet_actual: 31000,
    next_product_plan: 35000,
    next_billet_plan: 25000,
    reason_category: '소재 문제',
    reason_detail: '아침 소재 입고 지연으로 오전 작업 1시간 대기. 소재 준비팀 연락 지연.',
    action_today: '오후 작업량 증대를 통해 부분 만회.',
    recovery_plan: '',
    support_request: '',
    submit_status: 'saved',
    created_at: planDate + 'T09:00:00Z',
    updated_at: planDate + 'T14:00:00Z',
  },
  // 오늘 - R/M 주간 (미입력)
  {
    id: 'entry-3',
    report_id: 'report-today',
    user_id: 'user-woo-jaehan',
    user_name: '우재한 과장',
    equipment: 'R/M',
    shift: '주간',
    product_plan: 90000,
    product_actual: 0,
    billet_plan: 0,
    billet_actual: 0,
    next_product_plan: 100000,
    next_billet_plan: 0,
    submit_status: 'not_started',
    created_at: planDate + 'T09:00:00Z',
    updated_at: planDate + 'T09:00:00Z',
  },
  // 오늘 - P15 야간
  {
    id: 'entry-4',
    report_id: 'report-today',
    user_id: 'user-kim-hyun',
    user_name: '김현 차장',
    equipment: 'P15',
    shift: '야간',
    product_plan: 50000,
    product_actual: 0,
    billet_plan: 100000,
    billet_actual: 0,
    next_product_plan: 50000,
    next_billet_plan: 100000,
    submit_status: 'not_started',
    created_at: planDate + 'T09:00:00Z',
    updated_at: planDate + 'T09:00:00Z',
  },
  // 오늘 - P5 야간
  {
    id: 'entry-5',
    report_id: 'report-today',
    user_id: 'user-koo-byeongjun',
    user_name: '구병준 차장',
    equipment: 'P5',
    shift: '야간',
    product_plan: 30000,
    product_actual: 0,
    billet_plan: 20000,
    billet_actual: 0,
    next_product_plan: 35000,
    next_billet_plan: 25000,
    submit_status: 'not_started',
    created_at: planDate + 'T09:00:00Z',
    updated_at: planDate + 'T09:00:00Z',
  },
  // 오늘 - R/M 야간
  {
    id: 'entry-6',
    report_id: 'report-today',
    user_id: 'user-woo-jaehan',
    user_name: '우재한 과장',
    equipment: 'R/M',
    shift: '야간',
    product_plan: 110000,
    product_actual: 0,
    billet_plan: 0,
    billet_actual: 0,
    next_product_plan: 100000,
    next_billet_plan: 0,
    submit_status: 'not_started',
    created_at: planDate + 'T09:00:00Z',
    updated_at: planDate + 'T09:00:00Z',
  },
];

// 데모 목표값
export const DEMO_TARGETS: EquipmentTarget[] = [
  { id: 't1', equipment: 'P15', shift: '주간', product_target: 72500, billet_target: 75000, effective_date: '2026-01-01', created_at: '2026-01-01T00:00:00Z' },
  { id: 't2', equipment: 'P15', shift: '야간', product_target: 72500, billet_target: 75000, effective_date: '2026-01-01', created_at: '2026-01-01T00:00:00Z' },
  { id: 't3', equipment: 'P5', shift: '주간', product_target: 35000, billet_target: 25000, effective_date: '2026-01-01', created_at: '2026-01-01T00:00:00Z' },
  { id: 't4', equipment: 'P5', shift: '야간', product_target: 35000, billet_target: 25000, effective_date: '2026-01-01', created_at: '2026-01-01T00:00:00Z' },
  { id: 't5', equipment: 'R/M', shift: '주간', product_target: 100000, billet_target: 0, effective_date: '2026-01-01', created_at: '2026-01-01T00:00:00Z' },
  { id: 't6', equipment: 'R/M', shift: '야간', product_target: 100000, billet_target: 0, effective_date: '2026-01-01', created_at: '2026-01-01T00:00:00Z' },
];

// 기간별 생산 목표값
export const DEMO_PERIOD_TARGETS: ProductionPeriodTarget[] = [
  { id: 'pt-weekly', period: 'weekly', product_target: 0, billet_target: 0, effective_date: '2026-01-01', created_at: '2026-01-01T00:00:00Z' },
  { id: 'pt-monthly', period: 'monthly', product_target: 0, billet_target: 0, effective_date: '2026-01-01', created_at: '2026-01-01T00:00:00Z' },
  { id: 'pt-yearly', period: 'yearly', product_target: 0, billet_target: 0, effective_date: '2026-01-01', created_at: '2026-01-01T00:00:00Z' },
];
